package_builds:
    - name: nova
      url: "git://github.com/openstack/nova.git"
      branch: master
      git_master: "git://github.com/openstack/nova.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-nova.git"
      packager_branch: "master"
      build_docs: false

    - name: python-novaclient
      url: "git://github.com/openstack/python-novaclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-novaclient.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-python-novaclient.git"
      packager_branch: "master"
      build_docs: false

    - name: glance
      url: "git://github.com/openstack/glance.git"
      branch: master
      git_master: "git://github.com/openstack/glance.git"
      revision:
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-glance.git"
      packager_branch: "master"
      build_docs: false

    - name: python-glanceclient
      url: "git://github.com/openstack/python-glanceclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-glanceclient.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-python-glanceclient.git"
      packager_branch: "master"
      build_docs: false

    - name: keystone
      url: "git://github.com/openstack/keystone.git"
      branch: master
      git_master: "git://github.com/openstack/keystone.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-keystone.git"
      packager_branch: "master"
      build_docs: false

    - name: python-keystoneclient
      url: "git://github.com/openstack/python-keystoneclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-keystoneclient.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-python-keystoneclient.git"
      packager_branch: "master"
      build_docs: false

    - name: swift
      url: "git://github.com/openstack/swift.git"
      branch: master
      git_master: "git://github.com/openstack/swift.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-swift.git"
      packager_branch: "master"
      build_docs: false

    - name: python-swiftclient
      url: "git://github.com/openstack/python-swiftclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-swiftclient.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-python-swiftclient.git"
      packager_branch: "master"
      build_docs: false

    - name: cinder
      url: "git://github.com/openstack/cinder.git"
      branch: master
      git_master: "git://github.com/openstack/cinder.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-cinder.git"
      packager_branch: "master"
      build_docs: false

    - name: python-cinderclient
      url: "git://github.com/openstack/python-cinderclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-cinderclient.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-python-cinderclient.git"
      packager_branch: "master"
      build_docs: false

    - name: neutron
      url: "git://github.com/openstack/neutron.git"
      branch: master
      git_master: "git://github.com/openstack/neutron.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-neutron.git"
      packager_branch: "master"
      build_docs: false

    - name: python-neutronclient
      url: "git://github.com/openstack/python-neutronclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-neutronclient.git"
      revision:
      merge_master: false
      packager_url: "git://github.com/redhat-openstack/openstack-python-neutronclient.git"
      packager_branch: "master"
      build_docs: false

    - name: ceilometer
      url: "git://github.com/openstack/ceilometer.git"
      branch: master
      git_master: "git://github.com/openstack/ceilometer.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-ceilometer.git"
      packager_branch: "master"
      build_docs: false

    - name: python-ceilometerclient
      url: "git://github.com/openstack/python-ceilometerclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-ceilometerclient.git"
      revision:
      merge_master: false
      packager_url: "git://github.com/redhat-openstack/openstack-python-ceilometerclient.git"
      packager_branch: "master"
      build_docs: false

    - name: heat
      url: "git://github.com/openstack/heat.git"
      branch: master
      git_master: "git://github.com/openstack/heat.git"
      revision: 
      merge_master: true
      packager_url: "git://github.com/redhat-openstack/openstack-heat.git"
      packager_branch: "master"
      build_docs: false

    - name: python-heatclient
      url: "git://github.com/openstack/python-heatclient.git"
      branch: master
      git_master: "git://github.com/openstack/python-heatclient.git"
      revision:
      merge_master: false
      packager_url: "git://github.com/redhat-openstack/openstack-python-heatclient.git"
      packager_branch: "master"
      build_docs: false
