modules:
    - name: nova
      url: "git://github.com/stackforge/puppet-nova.git"
      branch: master
      git_master: "git://github.com/stackforge/puppet-nova.git"
      revision: 
      merge_master: false
    - name: glance
      url: "https://review.openstack.org/stackforge/puppet-glance"
      branch: master
      git_master: "git://github.com/stackforge/puppet-glance.git"
      revision: 
      merge_master: false
    - name: keystone
      url: "git://github.com/stackforge/puppet-keystone.git"
      branch: master
      git_master: "git://github.com/stackforge/puppet-keystone.git"
      revision: 
      merge_master: false
    - name: swift
      url: "git://github.com/stackforge/puppet-swift.git"
      branch: master
      git_master: "git://github.com/stackforge/puppet-swift.git"
      revision: 
      merge_master: false
    - name: cinder
      url: "git://github.com/stackforge/puppet-cinder.git"
      branch: master
      git_master: "git://github.com/stackforge/puppet-cinder.git"
      revision: 
      merge_master: false
    - name: neutron
      url: "https://review.openstack.org/stackforge/puppet-neutron"
      branch: master
      git_master: "git://github.com/stackforge/puppet-neutron.git"
      revision:
      merge_master: false
    - name: ceilometer
      url: "https://review.openstack.org/stackforge/puppet-ceilometer"
      branch: refs/changes/83/45083/1
      git_master: "https://review.openstack.org/stackforge/puppet-ceilometer"
      revision:
      merge_master: true
    - name: heat
      url: "git://github.com/stackforge/puppet-heat"
      branch: master
      git_master: "git://github.com/stackforge/puppet-heat.git"
      revision:
      merge_master: false
    - name: openstack
      url: "https://review.openstack.org/stackforge/puppet-openstack"
      branch: refs/changes/63/44763/2
      git_master: "https://review.openstack.org/stackforge/puppet-openstack"
      revision:
      merge_master: false

nodes:
    - name: nova1
      manifest: nova1.pp
